version: '3.6'

services:
  coursematierial:
    image: georgemihail/docker-circle
    ports:
      - 4000:80
    container_name: course_material
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
